### ISSUE TITLE
Server-side non-null check required for all date/time fields

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#612]
Safari for desktop [still does not support](https://caniuse.com/#search=date) native `input[type=date]`, and so does not enforce the `required` attribute. This causes an HTTP 500 to be returned to the user if they forget any fields.
Not (as previously thought) related to #604.

E.g.: https://sentry.io/organizations/camdram-webteam/issues/856807794/?project=1273126&referrer=github_plugin

```
ErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function setTimezone() on null in /var/www/camdram/production/releases/32/src/Acts/CamdramBundle/Form/Type/AuditionType.php:40
Stack trace:
#0 /var/www/camdram/production/releases/32/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Acts\CamdramBundle\Form\Type\AuditionType->Acts\CamdramBundle\Form\Type\{closure}(Object(Symfony\Component\Form\FormEvent), 'form.bind', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#1 /var/www/camdram/production/releases/32/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'form.bind', Object(Symfony\Component\Form\FormEvent))
#2 /var/www/camdram/production/releases/32/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php(33): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('form.bind', Object(Symfon
  File "src/Acts/CamdramBundle/Form/Type/AuditionType.php", line 40, in handleFatalError
    $endAtTime->setTimezone(new \DateTimezone('Europe/London'));
```

**Comment by GKFX** [comment]
See also Sentry issue: [CAMDRAM-WEB-8Q](https://sentry.io/organizations/camdram-webteam/issues/856807791/?project=1273126&referrer=github_plugin)

**Comment by GKFX** [comment]
Sentry issue: [CAMDRAM-WEB-CH](https://sentry.io/organizations/camdram-webteam/issues/991112645/?referrer=github_plugin)
